In [1]:
def getFirst(myList):
    return myList[0]

In [2]:
getFirst([1,2,3,4])

1

In [3]:
getFirst([i for i in range(1, 11)])

1

In [4]:
def getSum(myList):
    sum = 0
    for item in myList:
        sum = sum + item
    return sum

In [6]:
getSum([i for i in range(5, 7)])

11

In [7]:
def searchBinary(myList, item):
    first = 0
    last = len(myList) - 1
    foundFlag = False
    while(first <= last and not foundFlag):
        mid = (first + last) // 2
        if myList[mid] == item:
            foundFlag = True
        else:
            if item < myList[mid]:
                last = mid - 1
            else:
                first = mid + 1
    return foundFlag

In [8]:
searchBinary([i for i in range(1,10000,2)], 554)

False

In [10]:
searchBinary([i for i in range(1,1000000,2)], 444445)

True

In [11]:
list(filter(lambda x: x > 100, [-5, 200, 300, 1000]))

[200, 300, 1000]

In [14]:
list(filter(lambda x: x%2 == 0, [100,203, 500]))

[100, 500]

In [15]:
[i for i in range(1, 11) if i % 2 == 0]


[2, 4, 6, 8, 10]

In [16]:
list(map(lambda x: x ** 2, [11,22,33,44,55]))

[121, 484, 1089, 1936, 3025]

In [17]:
from functools import reduce
def doSum(x1, x2):
    return x1 + x2
x = reduce(doSum, [100,122,33,4,5,6])

In [18]:
x

270

In [20]:
x = {1,2,3,4}
y = {2,3,5,4}

In [21]:
x & y

{2, 3, 4}

In [22]:
y | x

{1, 2, 3, 4, 5}

In [23]:
w = y|x

In [24]:
w

{1, 2, 3, 4, 5}

In [25]:
Sets	Complexity
Add an element	O(1)
Remove an element	O(1)
Copy	O(n)

SyntaxError: invalid syntax (<ipython-input-25-ce48747e1f3f>, line 1)

In [26]:
import pandas as pd 
df = pd.DataFrame([['1', 'Fares', 32, True],
                    ['2', 'Elena', 23, False],
                     ['3', 'Steven', 40, True]])

In [27]:
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [28]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [29]:
df[['name', 'age']]
df.iloc[:, 3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [30]:
df.iloc[1:3, :]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [31]:
df[df.age > 30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [32]:
df[(df.age<35) & (df.decision == True)]

id   name  age  decision
0  1  Fares   32      True

In [34]:
import numpy as np
myMatrix = np.array([[11,12,13], [21,22,23], [31,32,33]])

In [35]:
myMatrix

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [36]:
myMatrix[myMatrix > 15]

array([21, 22, 23, 31, 32, 33])

In [37]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [39]:
myMatrix.T

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [40]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [41]:
print(type(myVector))

<class 'list'>


In [42]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [43]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items) - 1]
    def size(self):
        return len(self.items)

In [44]:
stack = Stack()

In [55]:
stack.push('Red')

In [56]:
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [57]:
stack.pop()

'Yellow'

In [58]:
stack.isEmpty()

False

In [12]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0, item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [13]:
queue = Queue()

In [14]:
queue.enqueue('Red')

In [15]:
queue.enqueue('Green')

In [16]:
queue.enqueue('Blue')

In [17]:
queue.enqueue('Yellow')

In [18]:
print(queue.size())

4


In [19]:
print(queue.dequeue())

Red


In [20]:
print(queue.dequeue())

Green


In [1]:
var1 = 1
var2 = 2
var1, var2 = var2, var1

In [2]:
print(var1, var2)

2 1


TypeError: object of type 'type' has no len()

In [6]:
list_1 = [i for i in range (20,27)]
lastElementIndex = len(list_1) - 1
print(0, list_1)
for idx in range(lastElementIndex):
    if list_1[idx] > list_1[idx + 1]:
        list_1[idx], list_1[idx + 1] = list_1[idx + 1], list_1[idx]
    print(idx+1, list_1)    

0 [20, 21, 22, 23, 24, 25, 26]
1 [20, 21, 22, 23, 24, 25, 26]
2 [20, 21, 22, 23, 24, 25, 26]
3 [20, 21, 22, 23, 24, 25, 26]
4 [20, 21, 22, 23, 24, 25, 26]
5 [20, 21, 22, 23, 24, 25, 26]
6 [20, 21, 22, 23, 24, 25, 26]
